### ISSUE TITLE
Python 3.6.9: No keyword 'text' in 'subprocess.Popen()'

### ISSUE THREAD

**Issue by kazmierz18** [micdmy/micsync#1] opened 2020-01-23 10:27 UTC
pwd /home/user/source
on cmd micsync --backup -s dfg
```python
Traceback (most recent call last):
  File "/usr/local/bin/micsync", line 19, in <module>
    program.sync()
  File "/usr/local/lib/python3.6/dist-packages/micsync/micsync.py", line 138, in sync
    self.mode.perform()
  File "/usr/local/lib/python3.6/dist-packages/micsync/mode.py", line 91, in perform
    dst, self.srcs), self.flags.verbose)
  File "/usr/local/lib/python3.6/dist-packages/micsync/flags.py", line 16, in getRsyncOptions
    srcs, dst, self.suspendPrintDirs) else Rsync.NO_MODIFY
  File "/usr/local/lib/python3.6/dist-packages/micsync/rsync.py", line 55, in shallModifyExisting
    suspendPrintDirs, dst)
  File "/usr/local/lib/python3.6/dist-packages/micsync/rsync.py", line 34, in _run
    args=command, stdout=subprocess.PIPE, text=True).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'
```
cfg file:
```json
{
    "configs": [ {
        "name": "My first CONFIGURATION, it contains 1 WORKING and 1 BACKUP",
            "work": [
                "/home/user/source"
            ],
            "backup": [
                "/home/user/backup"
            ]
    }
    ]
}
```

version 0.0.3.dev8
rsync  version 3.1.2  protocol version 31

**Comment by micdmy** [comment] 2020-01-23 10:30
Dear kazimierz18,

Thank you for your support.
Please attach your config file.
Your issue will be fixed as soon as possible.

BR
Micsync support team

**Comment by kazmierz18** [comment] 2020-01-23 10:32
micsync --tree .
```python
Traceback (most recent call last):
  File "/usr/local/bin/micsync", line 19, in <module>
    program.sync()
  File "/usr/local/lib/python3.6/dist-packages/micsync/micsync.py", line 138, in sync
    self.mode.perform()
  File "/usr/local/lib/python3.6/dist-packages/micsync/tree_mode.py", line 12, in perform
    options = self.flags.getRsyncOptions(dst, self.srcs) + Rsync.TREE
  File "/usr/local/lib/python3.6/dist-packages/micsync/flags.py", line 16, in getRsyncOptions
    srcs, dst, self.suspendPrintDirs) else Rsync.NO_MODIFY
  File "/usr/local/lib/python3.6/dist-packages/micsync/rsync.py", line 55, in shallModifyExisting
    suspendPrintDirs, dst)
  File "/usr/local/lib/python3.6/dist-packages/micsync/rsync.py", line 34, in _run
    args=command, stdout=subprocess.PIPE, text=True).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'
```

**Comment by micdmy** [comment] 2020-01-23 10:33
Dear kazimierz18,

If possible please attach result of 'tree' command of source and backup directories.
It will help us immensely.

BR
Micsync support team

**Comment by kazmierz18** [comment] 2020-01-23 10:34
```bash
┬─[user@user-VirtualBox:~/source]─[11:31:48 AM]
╰─>$ tree
.
├── dfg
└── file
```

**Comment by kazmierz18** [comment] 2020-01-23 10:35
Linux user-VirtualBox 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Python 3.6.9

**Comment by micdmy** [comment] 2020-01-24 06:38
Dear kazimierz18,

The problem you encountered was caused by the use of functionalities in 'subprocess' module that were introduced in python version 3.7. Please update you python to at least 3.7.

We will add proper requirements to micsync 'setup.py' in next vrsion to avoid this bug in future.

BR
Micsync support team

**Closed as completed** 2020-01-24 06:59 UTC
